<a href="https://colab.research.google.com/github/jose2049/ml-project-colab/blob/main/CampusDataSet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Campus data project
###José Álvarez

##Data preparation

In [27]:
import pandas as pd

In [28]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [29]:
df = pd.read_csv('/content/drive/MyDrive/Machine Learning/CampusWalkDataset_TemplateIDs_final.csv')

###Inspect the dataset structure

--- Weather Column ---
0      partly cloudy
1              sunny
2      partly cloudy
3      partly cloudy
4              sunny
           ...
194          unknown
195          unknown
196          unknown
197          unknown
198          unknown
Name: weather, Length: 199, dtype: object

--- First 10 rows of 'location_encoded' ---

0    0
1    1
2    5
3    7
4    5
5    0
6    3
7    4
8    5
9    6
Name: location_encoded, dtype: int64

The value at row index 0 in the 'weather' column is: partly cloudy

In [42]:

print("--- Teperature Column --- ")
print(df_encoded['temperature_c'])

# 2. Or display just the first 10 rows of that column for a cleaner view
print("\n--- First 10 rows of 'location_encoded' ---")
display(df_encoded['location_encoded'].head(10))

# 3. Get the value of a specific single row (e.g., row index 0) in that column
single_value = df_encoded['temperature_c'].iloc[50]
print(f"\nThe value at row index 0 in the 'temperature_c' column is: {single_value}")

--- Teperature Column ---
0       16
1       16
2       16
3       16
4       16
      ...
194    NaN
195    NaN
196    NaN
197    NaN
198    NaN
Name: temperature_c, Length: 199, dtype: object

--- First 10 rows of 'location_encoded' ---

0    0
1    1
2    5
3    7
4    5
5    0
6    3
7    4
8    5
9    6
Name: location_encoded, dtype: int64

The value at row index 0 in the 'temperature_c' column is: 17

#Checking temperature column
## **Fix points**
### decimal numbers
### mix between numbers and letters

# Checking dates column

##**Points to fix**

In [56]:
print("--- Dates rows  ---")
display(df_encoded['date'].iloc[90:115])

--- Dates rows  ---

90     25/09/2026
91     26/09/2026
92     27/09/2026
93     28/09/2026
94     23/09/2026
95     24/09/2026
96     25/09/2026
97     26/09/2026
98     27/09/2026
99     23/09/2026
100    23/09/2026
101    23/09/2026
102    23/09/2026
103    23/09/2026
104    23/09/2026
105    23/09/2026
106    23/09/2026
107    23/09/2026
108    23/09/2026
109    23/09/2026
110    23/09/2026
111    23/09/2026
112    23/09/2026
113    23/09/2026
114    23/09/2026
Name: date, dtype: object